@startuml

[*] --> CONSTRUCTION : Start
CONSTRUCTION : Initial State

CONSTRUCTION --> RUNNING
RUNNING --> BOOSTED
RUNNING --> BLOCKED
RUNNING --> BROKEN
BOOSTED --> BROKEN
BOOSTED --> RUNNING
BOOSTED --> BLOCKED
BLOCKED --> RUNNING
BROKEN --> RUNNING

@enduml
